BLOCKSDS ?= /opt/wonderful/thirdparty/blocksds/core
BLOCKSDSEXT ?= /opt/wonderful/thirdparty/blocksds/external
WONDERFUL_TOOLCHAIN ?= /opt/wonderful
NAME ?= game-blocksds
GAME_TITLE ?= Tower Defense DS
GAME_SUBTITLE ?= Sector 1 - Mechanicus
GAME_AUTHOR ?= Antigravity
GAME_ICON ?= icon.png
SOURCEDIRS := arm9/source
INCLUDEDIRS := arm9/include
BINDIRS ?=
DEFINES ?= -DDS_DEBUG_TRACE -DDS_AUTOTEST
include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
