BLOCKSDS ?= /opt/wonderful/thirdparty/blocksds/core
BLOCKSDSEXT ?= /opt/wonderful/thirdparty/blocksds/external
WONDERFUL_TOOLCHAIN ?= /opt/wonderful
NAME ?= game-blocksds
GAME_TITLE ?= NDS Game
GAME_SUBTITLE ?= BlocksDS test
GAME_AUTHOR ?= Agentic DS Dev
SOURCEDIRS := arm9/source
INCLUDEDIRS := arm9/include
BINDIRS := arm9/assets/samples
DEFINES := -DDS_DEBUG_TRACE -DDS_AUTOTEST
include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
